import os
from typing import TypedDict
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.graph import StateGraph, START, END
from tavily import TavilyClient

# Load environment variables
load_dotenv()

# ============================================================================
# PYDANTIC MODELS
# ============================================================================

class ResearchPlan(BaseModel):
    """Structured output from the Planner node."""
    questions: list[str] = Field(
        description="3 to 5 targeted research questions that together cover the full scope of the original query.",
        min_length=3,
        max_length=5
    )


# ============================================================================
# STATE DEFINITION
# ============================================================================

class ResearchState(TypedDict):
    """The complete state that flows through the LangGraph."""
    query: str                            # Original research query
    research_questions: list[str]         # Questions generated by planner
    search_results: dict[str, list[dict]] # {question: [{content, url}, ...]}
    final_report: str                     # Final markdown report from synthesizer
    conversation_context: str             # Previous Q&A for multi-turn awareness


# ============================================================================
# SYSTEM PROMPTS
# ============================================================================

PLANNER_SYSTEM_PROMPT = """You are a research planning specialist. Given a broad research query, decompose it into 3 to 5 precise, targeted sub-questions that together provide complete coverage of the topic.

Rules:
- Each question must be independently searchable (a web search for it should return useful results)
- Questions must NOT overlap in scope
- Questions must collectively cover the full original query
- Order them from foundational (context/background) to specific (impact/analysis)
- Do not number them or add prefixes
- Each question should be 1-2 sentences and end with a question mark

Return ONLY a JSON object matching the schema provided."""


SYNTHESIZER_SYSTEM_PROMPT = """You are a senior research analyst. You will be given:
1. An original research query
2. A set of targeted sub-questions
3. Web search results for each sub-question, with source URLs
4. Optional: Previous conversation context for follow-up awareness

Your task is to produce a comprehensive research report in markdown format.

The report MUST follow this exact structure:

# Research Report: [Restate the original query as a title]

## Executive Summary
2-3 sentences capturing the most important findings.

## Key Findings

### [Sub-Question 1]
Your synthesis of findings for this question. Cite sources inline as [source or domain](URL).

### [Sub-Question 2]
...repeat for each sub-question...

## Knowledge Gaps and Limitations
A bulleted list of specific information that was NOT found or was ambiguous in the search results.
Be concrete — name what is missing, not just "more research needed."
Examples of good gaps:
- No peer-reviewed data on GPU price elasticity post-2025
- Anthropic's H100 procurement figures are not publicly disclosed
- Limited information on [specific topic]

## Sources
A numbered list of all unique URLs cited in the report.

Rules:
- Do NOT fabricate facts or URLs
- If a sub-question returned no results, note it explicitly in both the finding section and the gaps section
- Write for a technically sophisticated audience
- Use present tense for current state, past tense for historical events
- Keep each Key Finding section to 150-250 words
- Do NOT make up numbers or statistics that were not in the search results"""


# ============================================================================
# NODE FUNCTIONS
# ============================================================================

def planner_node(state: ResearchState) -> dict:
    """
    Break down the broad query into 3-5 targeted research questions.
    Uses GPT-4o with structured output (Pydantic).
    """
    print(f"\n[PLANNER] Breaking down query: {state['query']}")

    llm = ChatOpenAI(model="gpt-4o", temperature=0, api_key=os.getenv("OPENAI_API_KEY"))
    structured_llm = llm.with_structured_output(ResearchPlan)

    messages = [
        SystemMessage(content=PLANNER_SYSTEM_PROMPT),
        HumanMessage(content=f"Query: {state['query']}")
    ]

    result: ResearchPlan = structured_llm.invoke(messages)

    print(f"[PLANNER] Generated {len(result.questions)} questions:")
    for i, q in enumerate(result.questions, 1):
        print(f"  {i}. {q}")

    return {"research_questions": result.questions}


def searcher_node(state: ResearchState) -> dict:
    """
    Execute Tavily searches for each research question sequentially.
    Collects results with content and URLs for the synthesizer.
    """
    print("\n[SEARCHER] Starting web searches...")

    tavily = TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))
    search_results = {}

    for question in state["research_questions"]:
        print(f"\n[SEARCHER] Searching: {question}")
        try:
            response = tavily.search(
                query=question,
                max_results=5,
                search_depth="advanced",  # "basic" for speed, "advanced" for quality
                include_raw_content=False  # Raw content bloats context window
            )
            results = [
                {"content": r["content"], "url": r["url"]}
                for r in response.get("results", [])
            ]
            search_results[question] = results
            print(f"[SEARCHER] Got {len(results)} results for: {question[:60]}...")
        except Exception as e:
            print(f"[SEARCHER] Error on '{question}': {e}")
            search_results[question] = []

    return {"search_results": search_results}


def synthesizer_node(state: ResearchState) -> dict:
    """
    Synthesize all search results into a comprehensive markdown report.
    Identifies knowledge gaps and creates citations.
    Optionally uses previous conversation context for follow-up awareness.
    """
    print("\n[SYNTHESIZER] Building comprehensive report...")

    # Format search evidence for the prompt
    evidence_blocks = []
    for question, results in state["search_results"].items():
        block = f"### Question: {question}\n"
        if not results:
            block += "No results found for this question.\n"
        else:
            for i, r in enumerate(results, 1):
                block += f"Source {i} [{r['url']}]:\n{r['content']}\n\n"
        evidence_blocks.append(block)

    evidence_text = "\n".join(evidence_blocks)

    llm = ChatOpenAI(model="gpt-4o", temperature=0.2, api_key=os.getenv("OPENAI_API_KEY"))

    # Build the user message with context if available
    user_content = f"Original Query: {state['query']}\n\n"

    if state.get("conversation_context"):
        user_content += f"Previous Conversation:\n{state['conversation_context']}\n\n"

    user_content += (
        f"Research Sub-Questions: {', '.join(state['research_questions'])}\n\n"
        f"Search Evidence:\n{evidence_text}"
    )

    messages = [
        SystemMessage(content=SYNTHESIZER_SYSTEM_PROMPT),
        HumanMessage(content=user_content)
    ]

    response = llm.invoke(messages)
    report = response.content

    print(f"[SYNTHESIZER] Report generated ({len(report)} characters)")
    return {"final_report": report}


# ============================================================================
# GRAPH CONSTRUCTION
# ============================================================================

def build_research_graph():
    """Build and compile the LangGraph state graph."""
    graph = StateGraph(ResearchState)

    # Register nodes
    graph.add_node("planner", planner_node)
    graph.add_node("searcher", searcher_node)
    graph.add_node("synthesizer", synthesizer_node)

    # Wire edges (linear pipeline)
    graph.add_edge(START, "planner")
    graph.add_edge("planner", "searcher")
    graph.add_edge("searcher", "synthesizer")
    graph.add_edge("synthesizer", END)

    return graph.compile()


# Compile the graph once at module level (singleton)
research_graph = build_research_graph()


# ============================================================================
# PUBLIC API
# ============================================================================

def run_research(query: str, conversation_context: str = "") -> str:
    """
    Public API for the research pipeline.
    Invoked by server.py (MCP) and app.py (Streamlit).

    Args:
        query: The research query or question.
        conversation_context: Optional previous Q&A for multi-turn awareness.

    Returns:
        A markdown-formatted research report.
    """
    print(f"\n{'='*60}")
    print(f"[RUN_RESEARCH] Starting research for: {query}")
    if conversation_context:
        print(f"[RUN_RESEARCH] Using conversation context ({len(conversation_context)} chars)")
    print(f"{'='*60}")

    try:
        initial_state: ResearchState = {
            "query": query,
            "research_questions": [],
            "search_results": {},
            "final_report": "",
            "conversation_context": conversation_context
        }

        final_state = research_graph.invoke(initial_state)
        return final_state["final_report"]

    except Exception as e:
        error_msg = f"Research pipeline error: {str(e)}"
        print(f"[RUN_RESEARCH] ERROR: {error_msg}")
        import traceback
        traceback.print_exc()
        return f"## Research Error\n\nAn error occurred during research:\n\n```\n{error_msg}\n```"
